# Supabase project — generated by Automate Everything

resource "supabase_project" "main" {
  organization_id   = var.supabase_organization_id
  name              = "app-db"
  database_password = var.supabase_db_password
  region            = "us-east-1"
}

output "supabase_project_ref" {
  value = supabase_project.main.ref
}

output "supabase_url" {
  value = "https://${supabase_project.main.ref}.supabase.co"
}
