# Vercel project — generated by Automate Everything
# Apply with: tofu init && tofu apply

resource "vercel_project" "main" {
  name      = "trellis-tst"
  framework = "vite"
}

# Environment variables are managed via the Vercel dashboard or CI/CD secrets.
# Add them here as vercel_project_environment_variable resources if needed.

output "vercel_project_id" {
  value = vercel_project.main.id
}
